title: My Portfolio
email: your-email@example.com
description: >-
  A clean, modern portfolio showcasing my work.
baseurl: "" # leave blank
url: "" # will set when deploying
theme: minima
markdown: kramdown
header_pages:
  - index.md
  - about.md
  - po
  - articles.html
  - logs.html
  - about.md
